app:
    resource: '@AppBundle/Controller/'
    type: rest

#TODO: create redirect from index page to doc http://symfony.com/doc/current/routing/redirect_in_config.html

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /api/doc
        permanent: true